package com.hsf301.efep.enums;

public enum ActionCaseValues {
    HOME,
    AUTHED_FAIL,
    LOGIN_FAIL,
    LOGIN_SUCCESS_CUSTOMER,
    LOGIN_SUCCESS_SHOP,
    REGISTER_FAIL,
    REGISTER_SUCCESS,
    SEARCH_FLOWER,
    SORT_FLOWER,
    ADD_TO_WISHLIST,
    UPDATE_WISHLIST,
    CLEAR_WISHLIST,
    CHECK_OUT,
    CREATE_FLOWER,
    UPDATE_FLOWER,
    DELETE_FLOWER,
    FLOWER_DETAIL,
    ORDER_HISTORY,
    SHOP_FLOWER;

    ActionCaseValues(){}
}
